spring.application.name=coa
server.port=8081
spring.datasource.url=${COA_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/coa?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${COA_DATASOURCE_USERNAME:root}
spring.datasource.password=${COA_DATASOURCE_PASSWORD:qwq233}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
